### ISSUE TITLE
svelte 4 final release checklist

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#10213]
### Describe the problem

don't want to forget anything!

### Describe the proposed solution

- [ ] maybe do one final pre-release to sanity check against
- [ ] run ecosystem CI
- [ ] exit pre-release
- [ ] announcement blog post
- [ ] default `create-svelte` to 4.x

### Importance

i cannot use SvelteKit without it

**Comment by benmccann** [comment]
doh! wrong repo
