### ISSUE TITLE
Review TODOs and deprecated code

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#1247]
There's a couple dozen TODOs. A lot of them look like things we might want to address for the next major, so filing this as a reminder

**Comment by avarun42** [comment]
This is probably closed by https://github.com/sveltejs/kit/pull/8019 right?

**Comment by benmccann** [comment]
No.
```
$ grep -r TODO packages/kit/src/ | wc -l
33
```

**Comment by Nic-Polumeyv** [comment]
`grep -r TODO packages/kit/src/ | wc -l` on current `version-3` gives 59. Full list below.

The ones tied to major version windows:

- `runtime/client/client.js:63` and `client.js:1949` say "rethink for SvelteKit 3 where we can assume Svelte 5"
- `utils/page_nodes.js:86` is tagged "TODO 3.0" (always return `current`, drop the `?? {}` fallbacks elsewhere)
- `core/config/index.js:165` goes away with the `lib` option
- `runtime/server/page/render.js:203`, `runtime/server/remote.js:364` and `runtime/server/utils.js:116` are tagged "TODO 4.0"
- `runtime/app/stores.js:1` is deliberately kept ("remove this file when enough people have migrated to Kit 3")

`public.d.ts` also still exports the `@deprecated removed in 3.0` stubs (`createEntries`, `csrf.checkOrigin`, `preloadStrategy`).

<details><summary>All 59, paths relative to <code>packages/kit/src</code></summary>

**core**
- [ ] `core/config/index.js:165` remove with the `lib` option
- [ ] `core/postbuild/analyse.js:269` `hooks.server.js` importing `read` lands in the entry chunk
- [ ] `core/postbuild/prerender.js:370` warn that query strings have no effect on statically-exported pages
- [ ] `core/sync/write_ambient.js:5` "get rid of this, it's useless"
- [ ] `core/sync/write_server.js:86` re-run when `src/app.html` or `src/error.html` change
- [ ] `core/utils.js:12` Windows issue
- [ ] `core/sync/write_tsconfig.js:172` `baseUrl` is removed in TypeScript 7.0

**exports**
- [ ] `exports/vite/build/build_server.js:163` explain why a file was loaded on the server (analysis build)
- [ ] `exports/vite/build/utils.js:96` "do we need this separately?"
- [ ] `exports/vite/dev/index.js:88` error overlay doesn't reliably show on every page load
- [ ] `exports/vite/dev/index.js:230` explain why a file was loaded on the server (dev)
- [ ] `exports/vite/dev/index.js:266` static vs dynamic imports, "investigate, submit fix"
- [ ] `exports/vite/index.js:244` is setting `root` from the final Vite config needed?
- [ ] `exports/vite/index.js:736` use composable filter API when supported
- [ ] `exports/vite/index.js:1545` may need to generate a sourcemap in future
- [ ] `exports/vite/index.js:1589` make service worker file configurable?
- [ ] `exports/node/index.js:140` use `request.readableAborted` once Node >= 22.17 is the minimum

**runtime/app**
- [ ] `runtime/app/server/remote/prerender.js:103` adapters could provide prerendered data more efficiently
- [ ] `runtime/app/server/remote/prerender.js:145` missing error/loading/current/status
- [ ] `runtime/app/server/remote/requested.js:171` "improve"
- [ ] `runtime/app/stores.js:1` remove when enough people have migrated to Kit 3

**runtime/client**
- [ ] `runtime/client/client.js:63` rethink for SvelteKit 3, overhaul client.js
- [ ] `runtime/client/client.js:1949` can break with forks, rethink for SvelteKit 3
- [ ] `runtime/client/client.js:584` same stale-data handling for `live_query_map`
- [ ] `runtime/client/client.js:604` ticks shouldn't be necessary, something in Svelte is buggy
- [ ] `runtime/client/client.js:722` use `mount()`
- [ ] `runtime/client/client.js:1430` client-side data reuse after discussion #6124
- [ ] `runtime/client/client.js:3126` load `errors` earlier?
- [ ] `runtime/client/client.js:3201` edge case if `stream()` read fails?
- [ ] `runtime/client/remote-functions/prerender.svelte.js:82` shouldn't be sending these specific headers
- [ ] `runtime/client/remote-functions/query-batch.svelte.js:29` batches with the same key possible?
- [ ] `runtime/client/remote-functions/query-live/instance.svelte.js:170` reconnect needs to hook into the router
- [ ] `runtime/client/remote-functions/query/instance.svelte.js:130` "our behavior here could be better"
- [ ] `runtime/client/remote-functions/query/instance.svelte.js:162` should be unnecessary, known bug
- [ ] `runtime/form-utils.js:358` hacky, private members accessed on proxy

**runtime/server**
- [ ] `runtime/server/page/actions.js:170` should this be a different error altogether?
- [ ] `runtime/server/page/csp.js:107` reinstate if strict-dynamic can be made to work
- [ ] `runtime/server/page/csp.js:292` warn?
- [ ] `runtime/server/page/csp.spec.js:45` re-enable when strict-dynamic in dev returns
- [ ] `runtime/server/page/index.js:54` 404 should sometimes be 500, unclear how to differentiate
- [ ] `runtime/server/page/load_data.js:37` calculate with PageNodes, layouts could set `trailingSlash`
- [ ] `runtime/server/page/render.js:28` rename this function/module
- [ ] `runtime/server/page/render.js:88` inline_styles if a client entry point is added
- [ ] `runtime/server/page/render.js:91` `svelte/server` should expose `RenderOutput`
- [ ] `runtime/server/page/render.js:168` default error component undefined sometimes
- [ ] `runtime/server/page/render.js:366` revert to top-level await once WebKit bug 242740 is fixed
- [ ] `runtime/server/page/render.js:585` convert `setHeaders` headers to http-equiv where possible
- [ ] `runtime/server/page/render.js:619` flush chunks earlier
- [ ] `runtime/server/respond.js:763` renaming `e` to `error` breaks a Vite transform
- [ ] `runtime/server/respond.js:766` should endpoint `HttpError` be handled at the endpoint?
- [ ] `runtime/server/page/render.js:203` TODO 4.0, make async and await `handled`
- [ ] `runtime/server/remote.js:364` TODO 4.0, remove the `Promise.resolve(...)`
- [ ] `runtime/server/utils.js:116` TODO 4.0, await instead of handling the non-Promise case

**types / utils**
- [x] `utils/page_nodes.js:86` TODO 3.0, always return `current`, drop `?? {}` elsewhere
- [ ] `types/internal.d.ts:218` supply default component if missing
- [ ] `types/internal.d.ts:304` "is this outdated now with the recent changes?"
- [ ] `utils/escape.js:28` use lookbehind assertions once widely supported
- [ ] `utils/page_nodes.js:80` override server config value with the universal value?
- [ ] `utils/shared-iterator.js:215` investigate if this needs to be implemented

</details>

**Comment by Nic-Polumeyv** [comment]
The escape.js lookbehind TODO is addressed in #16407, using `\p{Surrogate}` rather than lookbehind. The top-level-await TODO in render.js is still blocked, the WebKit bug (242740) was fixed upstream in April but hasn't shipped in a Safari release yet. The `readableAborted` TODO from #14715 needs the Node floor at >=22.17 rather than the current >=22 from #12548, which only gets to move while 3.0 is unreleased, so I've opened #16409 with the engines bump and the simplification.

Edit: #16409 was declined, see https://github.com/sveltejs/kit/pull/16409#issuecomment-5013455450, so the TODO stands.

**Comment by Nic-Polumeyv** [comment]
write_ambient.js only writes `/// <reference types="@sveltejs/kit" />` now and nothing references ambient.d.ts on version-3. Removal moved to the types overhaul in #16458.
